# Generated by Django 6.0.7 on 2026-08-03 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0003_message_is_read_chat_message_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
    ]
