# Generated by Django 6.0.7 on 2026-07-31 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Tytuł')),
                ('description', models.TextField(max_length=500, verbose_name='Opis')),
                ('date', models.DateField(verbose_name='Data wydarzenia')),
                ('time', models.TimeField(verbose_name='Godzina wydarzenia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Godzina utworzenia wydarzenia')),
                ('number_of_seats', models.IntegerField(default=0, verbose_name='Liczba dostępnych miejsc')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Cena')),
                ('meeting_city', models.CharField(max_length=50, verbose_name='Miasto')),
                ('meeting_region', models.CharField(max_length=50, verbose_name='Województwo')),
                ('street', models.CharField(max_length=40, verbose_name='Ulica')),
            ],
        ),
    ]
