# Generated by Django 6.0.7 on 2026-08-04 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participations', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participation',
            name='is_waiting',
        ),
    ]
