# Generated by Django 6.0.7 on 2026-07-31 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=100, verbose_name='komentarz')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
